name: CI

on:
  push:
    branches: ["main", "feature/**", "fix/**"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Ruff (lint)
        run: ruff check . --exit-zero
      - name: Ruff (format check)
        continue-on-error: true
        run: ruff format --check .
      - name: Black (check)
        continue-on-error: true
        run: black --check .
      - name: Mypy (warn-only)
        continue-on-error: true
        run: mypy .