name: Convert DOCX to source/docs

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install converter dependency
        run: |
          python -m pip install --upgrade pip
          pip install python-docx
      - name: Run converter
        run: |
          if [ -f tools/convert_docx.py ]; then
            python tools/convert_docx.py
          else
            echo "Converter not found (tools/convert_docx.py). Skipping."
          fi
      - name: Commit converted files (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: convert .docx to source/docs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          add_options: "-A"